PackageIdentifier: Microsoft.Git
PackageVersion: 2.31.1.vfs.0.1
PackageName: Microsoft Git
Publisher: Microsoft Corporation
Moniker: microsoft-git
PackageUrl: https://aka.ms/ms-git
Tags: [ microsoft-git ]
License: Copyright (C) Microsoft Corporation
ShortDescription: |
  Git distribution to support monorepo scenarios.
  Note: This is not Git for Windows. Unless you are working in a monorepo and require
  specific Git modifications, please run `winget install git` to start using Git for Windows.
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/git/releases/download/v2.31.1.vfs.0.1/Git-2.31.1.vfs.0.1-64-bit.exe
  InstallerType: inno
  InstallerSha256: 2dcfc36be1a6cd38db517d59aff0c23e02b0f7bdb568048fcdfa10d52b555993
  InstallerSwitches:
    Custom: /COMPONENTS="AUTOUPDATE"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0