PackageIdentifier: Microsoft.Git
PackageVersion: 2.32.0.0.0
PackageName: Microsoft Git
Publisher: The Git Client Team at GitHub
Moniker: microsoft-git
PackageUrl: https://aka.ms/ms-git
Tags: [ microsoft-git ]
License: GPLv2
ShortDescription: |
  Git distribution to support monorepo scenarios.
  Note: This is not Git for Windows. Unless you are working in a monorepo and require
  specific Git modifications, please run `winget install git` to start using Git for Windows.
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/git/releases/download/v2.32.0.vfs.0.0/Git-2.32.0.vfs.0.0-64-bit.exe
  InstallerType: inno
  InstallerSha256: 73fe3e86ae419b7f63f87635850dc5d3c8285379e28b765e67501e502d4588b1
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0